#!/bin/bash
#SBATCH 

# module loading
module purge
module load R

# current directory
pwd

# commands start
mkdir /mnt/stsi/stsi1/ptseng/UKBB_Resources/ldpred2/chr${chr}
mkdir /scratch_ssd/temp

Rscript ldpred2_fileprep.r \
    --chromosome ${chr} \
    --file /gpfs/home/ptseng/Torkamani_Projects/20210901_PD_UKBB/ltfh_paper_analysis/PD.sumstats.reduced \
    --CHR CHR \
    --POS POS \
    --A0 A1 \
    --A1 A2 \

rsync -rtv /scratch_ssd/temp.* /mnt/stsi/stsi1/ptseng/UKBB_Resources/ldpred2/chr${chr}/
rm -rf /scratch_ssd/*